### ISSUE TITLE
It does not work in Bash in Windows

### ISSUE THREAD

**Issue by sole** [sole/cinnabarify#3]
Getting a big error right when starting to get source code, so essentially an issue with git-cinnabar not being quite happy with this environment.

```
Fetching mozilla
Traceback (most recent call last):
  File "/mnt/c/data/git-cinnabar/git-remote-hg", line 48, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/mnt/c/data/git-cinnabar/git-remote-hg", line 42, in main
    helper.run()
  File "/mnt/c/data/git-cinnabar/cinnabar/remote_helper.py", line 110, in run
    func(*args)
  File "/mnt/c/data/git-cinnabar/cinnabar/remote_helper.py", line 313, in import_
    self._branchmap.names())
  File "/mnt/c/data/git-cinnabar/cinnabar/hg/__init__.py", line 577, in getbundle
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/mercurial/wireproto.py", line 293, in getbundle
    f = self._callstream("getbundle", **opts)
  File "/usr/lib/python2.7/dist-packages/mercurial/httppeer.py", line 145, in _callstream
    raise error.OutOfBandError(resp.read())
mercurial.error.OutOfBandError: incompatible Mercurial client; bundle2 required
(see https://www.mercurial-scm.org/wiki/IncompatibleClient)

fatal: bad object 0000000000000000000000000000000000000000
error: hg::https://hg.mozilla.org/mozilla-unified did not send all necessary objects

error: Could not fetch mozilla
```

Filed issue in git-cinnabar itself: https://github.com/glandium/git-cinnabar/issues/112

**Comment by sole** [comment]
Apparently the version of Mercurial installed in Bash in windows is too old. I wonder if it can be updated using some PPA?
